- name: Install syslog-ng
  pkgng: name=syslog-ng

- name: Enable syslog-ng
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^syslog_ng_enable
    line: syslog_ng_enable="YES"

- name: Disable syslog
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^syslogd_enable
    line: syslogd_enable="NO"


- name: Stop syslog
  service: name=syslogd state=stopped

- name: Start syslog-ng
  service: name=syslog-ng state=restarted
